apiVersion: v1
kind: Pod
metadata:
  name: postgress-app
  labels:
    name: postgress-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgress
      image: postgress:9.4
      ports:
        - containerPort: 5432
