apiVersion: v1
kind: Pod
metadata:
  name: reddis-app
  labels:
    name: reddis-pod
    app: demo-voting-app
spec:
  containers:
    - name: reddis
      image: reddis
      ports:
        - containerPort: 6379
